---
title: "Problem 3"
author: "He Jin & Chuhan Zhou"
date: "11/15/2017"
---

### Data Description  

In this assignment, we used the Instacart dataset to complete analysis and draw interactive charts. **Instacart** is an online grocery service that supports online-shopping from local stores. This dataset contains 1,384,617 observations of 131,209 unique users, where each row in the dataset is a product of an order. There is a single order per user in this dataset.

Below are 15 variables in this dataset:

*  order_id: order identifier  
*  product_id: product identifier  
*  add_to_cart_order: order in which each product was added to cart  
*  reordered: 1 if this prodcut has been ordered by this user in the past, 0 otherwise  
*  user_id: customer identifier  
*  eval_set: which evaluation set this order belongs in (Note that the data for use in this class is exclusively from the ???train??? eval_set)  
*  order_number: the order sequence number for this user (1=first, n=nth)  
*  order_dow: the day of the week on which the order was placed  
*  order_hour_of_day: the hour of the day on which the order was placed  
*  days_since_prior_order: days since the last order, capped at 30, NA if order_number=1  
*  product_name: name of the product  
*  aisle_id: aisle identifier  
*  department_id: department identifier  
*  aisle: the name of the aisle  
*  department: the name of the department  


### Problem 1
 **The solution for problem 1 is** [here](https://harksoul.github.io/p8105_hw6_hj2479_p1/)  
 **The github repo for problem 1 is** [here](https://github.com/Harksoul/p8105_hw6_hj2479_p1/)

**Comments for problem 1:**    
 
  For the first graph, we showed the number of orders in different departments using the bar plots, which indicates that items from department produce are most frequently ordered.
  
  In the second graph, we changed the variable department to the aisle and made a scatterplot, thus we can find out the most popular kind of product in this dataset. And it shows that fresh fruits and fresh vegetables are the most popular aisles.
  
  Last graph we chose to use the boxplot to show the distribution of order time for relatively popular aisles.
  
  
  
### Problem 2   
 **The solution for problem 2 is** 
[here](http://harksoul.shinyapps.io/problem2/)  

**Comments for problem 2:**  
  
  First in Chart A, we made a bar plot showing the distribution of the most popular products in each department. Additionally, we added a slider filter to control the number of ordered items for the different department.
   
  Secondly in Chart B, we compared the number of orders for different aisles in each department. In the produce department, fresh fruits and vegetables are most frequently ordered.
 
  Last in Chart C, we intended to plot the distribution of order time for each aisle, we again used the box plot and found that Healthier snacks are usually ordered earlier in the day.

### Problem 3  
  **The github repo for problem 3** 
[here](https://github.com/Harksoul/p8106_hw6_p3)  
